import { AboutPage, type AboutPageContent } from "@/components/about-page";
import { englishHomeContent } from "@/content/en/home";
import { englishNavigationLabels } from "@/content/en/navigation";
import { createLocalizedPageMetadata } from "@/lib/metadata";

export const englishAboutContent = {
  metadata: { title: "About Our Heating & Plumbing Service in Šiauliai", description: "Learn about Žemaitija Heat & Home's practical approach to residential heating, heat pumps and plumbing around Šiauliai. A portfolio case study." },
  hero: { eyebrow: "About Žemaitija Heat & Home", title: "A practical local focus on homes and the work they need.", description: "Žemaitija Heat & Home is a small residential heating and plumbing company serving customers around Šiauliai and the wider Žemaitija region.", contactLabel: "Tell us about your property", note: { eyebrow: "Our focus", title: "Residential work, clearly explained.", description: "From an individual repair to a heating upgrade or renovation, the approach begins with understanding the home, the work required and the appropriate next step." } },
  residentialFocus: { eyebrow: "Residential focus", title: "Work centred on people’s homes.", description: "The service is intended for residential properties and the practical heating and plumbing decisions that come with owning, managing or improving a home.", items: [
    { title: "Homeowners", description: "Everyday repairs, planned improvements and new installations." }, { title: "Landlords", description: "Residential heating and plumbing work for managed properties." }, { title: "People renovating", description: "Heating and plumbing changes considered alongside the wider project." }, { title: "Rural households", description: "Enquiries from villages and rural properties across the service area." }, { title: "Heating upgrades", description: "Homeowners reviewing an ageing system or considering a heat pump." }, { title: "Repairs and call-outs", description: "Customers who need a plumbing or heating problem assessed." },
  ] },
  principles: { eyebrow: "What customers can expect", title: "Clear working principles instead of vague promises.", description: "A reliable experience starts with how the enquiry is handled and how the proposed work is explained.", items: [
    { title: "Understand the job first", description: "Start with the property, the current system or fixture, and what needs repairing or changing before proposing work." }, { title: "Explain the next steps", description: "Make clear what information is needed, whether an assessment may help and how the enquiry can move forward." }, { title: "Consider the whole property", description: "For an installation or renovation, account for the existing setup, layout and related work where it affects the proposed scope." }, { title: "Confirm local coverage", description: "Check the property location and type of job against the normal service area before making arrangements." }, { title: "Distinguish urgent and planned work", description: "Gather the right details for an urgent fault while giving planned maintenance, upgrades and renovations an appropriate process." }, { title: "Keep the work practical", description: "Use straightforward language and a scope that responds to the home and the job without adding unnecessary complexity." },
  ] },
  process: { eyebrow: "How we approach work", title: "A sensible path from enquiry to scope.", description: "The exact route depends on the job, but the general process keeps the property, the work and the next decision clear.", steps: [
    { title: "Get in touch", description: "Share the property location and a short description of the problem or planned work." }, { title: englishHomeContent.process.steps[1].title, description: "Talk through what is needed, what is already in place and any relevant plans or concerns." }, { title: "Assess where needed", description: "Arrange a site assessment when the property or proposed work needs to be reviewed in person." }, { title: "Clarify scope and next steps", description: "Explain the work being considered and any information or decisions needed before proceeding." }, { title: "Discuss a quotation", description: "Where appropriate, review the proposed scope and quotation before agreeing how to move forward." },
  ] },
  localService: { eyebrow: "Local service", title: "Šiauliai and the wider Žemaitija region.", description: "The normal service area extends approximately 50 km around Šiauliai and includes surrounding towns, villages and rural homes. Each enquiry is checked using the exact location and nature of the job.", linkLabel: "Check the service area", radiusAriaLabel: "Normal service radius", radiusValue: "Approximately 50 km", radiusDescription: "Normal service radius around Šiauliai" },
  services: { eyebrow: englishHomeContent.services.eyebrow, title: "Support for repairs and planned work.", description: "Choose the service that best matches what is happening in your home or what you are planning next.", items: [
    { title: englishNavigationLabels.heating, description: "Installation, repairs, maintenance and upgrades.", path: "/heating", linkLabel: englishHomeContent.services.items[0].link.label }, { title: englishNavigationLabels.heatPumps, description: "Suitability, assessment and planned installation.", path: "/heat-pumps", linkLabel: englishHomeContent.services.items[1].link.label }, { title: englishNavigationLabels.plumbing, description: "Domestic repairs, fixtures and renovation work.", path: "/plumbing", linkLabel: englishHomeContent.services.items[2].link.label }, { title: englishNavigationLabels.emergencyRepairs, description: "Information for urgent heating and plumbing enquiries.", path: "/emergency-repairs", linkLabel: englishHomeContent.enquiry.emergencyLink.label },
  ] },
  finalCta: { title: "Tell us about your home and the work required.", description: "Share the property location, describe the heating or plumbing job and explain what you would like help with. We can discuss the enquiry and the appropriate next steps.", contactLabel: englishHomeContent.enquiry.contactLink.label },
} as const satisfies AboutPageContent;

export const metadata = createLocalizedPageMetadata({ ...englishAboutContent.metadata, path: "/about", locale: "en" });
export default function EnglishAboutPage() { return <AboutPage content={englishAboutContent} locale="en" />; }
