import { AboutPage, type AboutPageContent } from "@/components/about-page";
import { lithuanianHomeContent } from "@/content/lt/home";
import { lithuanianNavigationLabels } from "@/content/lt/navigation";
import { lithuanianHeatingContent } from "@/content/lt/pages/heating";
import { createLocalizedPageMetadata } from "@/lib/metadata";

export const lithuanianAboutContent = {
  metadata: { title: "Apie mūsų šildymo ir santechnikos paslaugas Šiauliuose", description: "Sužinokite apie praktišką Žemaitija Heat & Home požiūrį į gyvenamųjų namų šildymą, šilumos siurblius ir santechniką Šiauliuose. Demonstracinis projektas." },
  hero: { eyebrow: "Apie Žemaitija Heat & Home", title: "Praktiškas vietinis požiūris į namus ir jiems reikalingus darbus.", description: "Žemaitija Heat & Home – nedidelė gyvenamųjų namų šildymo ir santechnikos įmonė, aptarnaujanti klientus Šiauliuose ir platesniame Žemaitijos regione.", contactLabel: "Papasakokite apie savo objektą", note: { eyebrow: "Mūsų dėmesys", title: "Gyvenamųjų namų darbai, paaiškinti aiškiai.", description: "Nuo pavienio remonto iki šildymo sistemos atnaujinimo ar renovacijos – viskas prasideda nuo namo, reikalingų darbų ir tinkamo kito žingsnio supratimo." } },
  residentialFocus: { eyebrow: "Dėmesys gyvenamiesiems namams", title: "Darbai, orientuoti į žmonių namus.", description: "Paslaugos skirtos gyvenamiesiems objektams ir praktiniams šildymo bei santechnikos sprendimams, kylantiems valdant, prižiūrint ar gerinant namus.", items: [
    { title: "Namų savininkai", description: "Kasdienis remontas, planuojami patobulinimai ir naujas montavimas." }, { title: "Nuomotojai", description: "Šildymo ir santechnikos darbai nuomojamuose ar prižiūrimuose gyvenamuosiuose objektuose." }, { title: "Renovuojantys būstą", description: "Šildymo ir santechnikos pakeitimai derinami su bendru renovacijos projektu." }, { title: "Kaimo vietovių namai", description: "Užklausos iš kaimų ir kaimo vietovių objektų visoje aptarnavimo teritorijoje." }, { title: "Šildymo sistemos atnaujinimas", description: "Namų savininkams, vertinantiems senstančią sistemą ar svarstantiems šilumos siurblį." }, { title: "Remontas ir iškvietimai", description: "Klientams, kuriems reikia įvertinti santechnikos ar šildymo problemą." },
  ] },
  principles: { eyebrow: "Ko gali tikėtis klientai", title: "Aiškūs darbo principai vietoje neapibrėžtų pažadų.", description: "Patikima paslauga prasideda nuo to, kaip priimama užklausa ir kaip paaiškinami siūlomi darbai.", items: [
    { title: "Pirmiausia suprasti darbus", description: "Prieš siūlant darbus reikia suprasti objektą, esamą sistemą ar įrangą ir tai, ką reikia remontuoti ar keisti." }, { title: "Paaiškinti tolesnius veiksmus", description: "Aiškiai nurodyti, kokios informacijos reikia, ar naudinga atlikti įvertinimą ir kaip užklausa gali judėti pirmyn." }, { title: "Įvertinti visą objektą", description: "Montuojant ar renovuojant reikia atsižvelgti į esamą sistemą, išplanavimą ir susijusius darbus, jei jie turi įtakos siūlomai darbų apimčiai." }, { title: "Patvirtinti aptarnavimo galimybę", description: "Prieš susitariant dėl darbų patikrinti objekto vietą ir darbų pobūdį pagal įprastą aptarnavimo teritoriją." }, { title: "Atskirti skubius ir planuojamus darbus", description: "Skubiam gedimui surinkti tinkamą informaciją, o planinei priežiūrai, atnaujinimams ir renovacijai taikyti tinkamą procesą." }, { title: "Išlaikyti praktišką požiūrį", description: "Naudoti aiškią kalbą ir darbų apimtį, kuri atitinka namą bei užduotį, nepridedant nereikalingo sudėtingumo." },
  ] },
  process: { eyebrow: lithuanianHeatingContent.process.eyebrow, title: "Aiškus kelias nuo užklausos iki darbų apimties.", description: "Tikslus procesas priklauso nuo darbų, tačiau bendra eiga padeda aiškiai suprasti objektą, darbus ir kitą sprendimą.", steps: [
    { title: lithuanianHomeContent.process.steps[0].title, description: "Nurodykite objekto vietą ir trumpai aprašykite problemą arba planuojamus darbus." }, { title: lithuanianHomeContent.process.steps[1].title, description: "Aptarkite, ko reikia, kas jau įrengta ir kokie planai ar rūpesčiai gali būti svarbūs." }, { title: "Įvertinti, jei reikia", description: "Kai būtina įvertinti objektą ar planuojamus darbus vietoje, susitariama dėl apsilankymo." }, { title: "Patikslinti darbų apimtį ir tolesnius veiksmus", description: "Paaiškinti svarstomus darbus ir informaciją ar sprendimus, kurių reikia prieš tęsiant." }, { title: "Aptarti kainos pasiūlymą", description: "Kai tinkama, prieš susitariant dėl tolesnių veiksmų peržiūrėti siūlomą darbų apimtį ir kainos pasiūlymą." },
  ] },
  localService: { eyebrow: "Vietinės paslaugos", title: lithuanianHomeContent.region.heading, description: "Įprasta aptarnavimo teritorija tęsiasi maždaug 50 km aplink Šiaulius ir apima aplinkinius miestus, kaimus bei kaimo vietovių namus. Kiekviena užklausa tikrinama pagal tikslią vietą ir darbų pobūdį.", linkLabel: "Patikrinti aptarnavimo teritoriją", radiusAriaLabel: "Įprastas aptarnavimo spindulys", radiusValue: "Maždaug 50 km", radiusDescription: "Įprastas aptarnavimo spindulys aplink Šiaulius" },
  services: { eyebrow: lithuanianHomeContent.services.eyebrow, title: "Pagalba tiek remontui, tiek planuojamiems darbams.", description: "Pasirinkite paslaugą, kuri geriausiai atitinka tai, kas vyksta jūsų namuose arba ką planuojate toliau.", items: [
    { title: lithuanianNavigationLabels.heating, description: "Montavimas, remontas, priežiūra ir atnaujinimas.", path: "/heating", linkLabel: lithuanianHomeContent.services.items[0].link.label }, { title: lithuanianNavigationLabels.heatPumps, description: "Tinkamumo vertinimas, objekto įvertinimas ir planuojamas montavimas.", path: "/heat-pumps", linkLabel: lithuanianHomeContent.services.items[1].link.label }, { title: lithuanianNavigationLabels.plumbing, description: "Buitinis remontas, santechnikos įranga ir renovacijos darbai.", path: "/plumbing", linkLabel: lithuanianHomeContent.services.items[2].link.label }, { title: lithuanianNavigationLabels.emergencyRepairs, description: "Informacija dėl skubių šildymo ir santechnikos užklausų.", path: "/emergency-repairs", linkLabel: lithuanianHomeContent.enquiry.emergencyLink.label },
  ] },
  finalCta: { title: "Papasakokite apie savo namus ir reikalingus darbus.", description: "Nurodykite objekto vietą, aprašykite šildymo ar santechnikos darbus ir paaiškinkite, kokios pagalbos reikia. Galėsime aptarti užklausą ir tinkamus tolesnius veiksmus.", contactLabel: lithuanianHomeContent.enquiry.contactLink.label },
} as const satisfies AboutPageContent;

export const metadata = createLocalizedPageMetadata({ ...lithuanianAboutContent.metadata, path: "/about", locale: "lt", availableLocales: [] });
export default function LithuanianAboutPage() { return <AboutPage content={lithuanianAboutContent} locale="lt" />; }
