import { ServiceAreaPage, type ServiceAreaPageContent } from "@/components/service-area-page";
import { lithuanianHomeContent } from "@/content/lt/home";
import { lithuanianNavigationLabels } from "@/content/lt/navigation";
import { lithuanianHeatingContent } from "@/content/lt/pages/heating";
import { createLocalizedPageMetadata } from "@/lib/metadata";

export const lithuanianServiceAreaContent = {
  metadata: { title: "Šildymo ir santechnikos aptarnavimo teritorija aplink Šiaulius", description: "Patikrinkite, ar aptarnaujame gyvenamųjų namų šildymo, šilumos siurblių, santechnikos ir skubaus remonto užklausas maždaug 50 km atstumu nuo Šiaulių. Demonstracinis projektas." },
  hero: { eyebrow: "Vietinės paslaugos gyvenamiesiems namams · Žemaitija", title: "Šildymo ir santechnikos paslaugos aplink Šiaulius.", description: "Mūsų įprasta darbo teritorija tęsiasi maždaug 50 km nuo Šiaulių ir apima aplinkinius miestus, kaimus bei kaimo vietovių namus platesniame Žemaitijos regione. Tiksli aptarnavimo galimybė tikrinama kiekvienai užklausai atskirai.", contactLabel: lithuanianHomeContent.region.noteHeading },
  visual: { centre: "Šiauliai", radius: "≈ 50 km", title: "Orientacinis įprastas aptarnavimo spindulys", description: "Šiauliai yra geografinis atskaitos taškas. Schema yra orientacinė ir neatspindi tikslios aptarnavimo ribos." },
  coverage: { eyebrow: "Pagrindinė aptarnavimo teritorija", title: "Įprastas darbo spindulys, tikrinamas kiekvienai užklausai.", description: "Maždaug 50 km spindulys padeda apibūdinti teritoriją, kurią paprastai aptarnaujame. Tai nėra garantija, kad kiekvienas objektas šioje zonoje bus automatiškai priimtas.", items: [
    { title: "Šiauliai – atskaitos taškas", description: "Aptarnavimo teritorija apibrėžiama Šiaulių atžvilgiu, kad namų savininkams būtų aiškus geografinis atskaitos taškas." }, { title: "Miestai ir kaimai", description: "Įprasta darbo teritorija apima gyvenamuosius objektus aplinkinėse regiono gyvenvietėse." }, { title: "Maždaug 50 km", description: "Šis spindulys yra praktinis orientyras, o ne tiksli riba ar automatinė aptarnavimo zona." }, { title: "Kiekviena užklausa tikrinama atskirai", description: "Tiksli objekto vieta ir darbų pobūdis padeda nustatyti, ar užklausa patenka į įprastą aptarnavimo teritoriją." },
  ] },
  checkerSection: { eyebrow: "Vietovės patikrinimas", title: "Patikrinkite savo vietovę.", description: "Įprasta aptarnavimo teritorija yra maždaug 50 km aplink Šiaulius, tačiau kiekviena vieta tikrinama atskirai. Įveskite miestą, kaimą, pašto kodą ar objekto vietą ir perduokite ją į užklausos formą.", checker: {
    fieldLabel: "Miestas, kaimas arba pašto kodas", placeholder: "Kuršėnai", submitLabel: "Patikrinti vietovę", loadingLabel: "Tikrinama vietovė…", fieldHint: "Įveskite vietą, kurią norite perduoti į užklausos formą.", validation: { empty: "Įveskite miestą, kaimą, pašto kodą arba objekto vietą.", invalid: "Vietai naudokite įprastas raides, skaičius ir adreso skyrybos ženklus." }, enquiryLabel: "Pateikti užklausą dėl šios vietos", attribution: "Vietovės paieška © OpenStreetMap autoriai",
  } },
  locationDetails: { eyebrow: "Kaip patikrinti savo vietovę", title: "Pateikite objekto informaciją kartu su užklausa.", description: "Keli praktiniai duomenys padeda patvirtinti, ar objektas patenka į įprastą aptarnavimo teritoriją ir ar darbus galima aptarti toliau.", items: [
    { title: "Miestas arba kaimas", description: "Nurodykite gyvenvietę arba vietovę, kurioje yra objektas." }, { title: "Objekto adresas", description: "Pateikite pakankamai adreso informacijos, kad būtų galima patikrinti vietą." }, { title: "Reikalinga paslauga", description: "Nurodykite, ar užklausa susijusi su šildymu, šilumos siurbliu, santechnika ar remontu." }, { title: "Planuojama arba skubu", description: "Paaiškinkite, ar planuojate būsimus darbus, ar reikia skubiai įvertinti problemą." },
  ], noteTitle: "Kodėl svarbus darbų pobūdis", noteDescription: "Vieta vertinama kartu su reikalinga paslauga ir darbų pobūdžiu. Susisiekdami pateikite abu duomenis, kad aptarnavimo galimybę būtų galima įvertinti pagal tinkamą informaciją.", contactLabel: "Siųsti vietovės ir paslaugos informaciją" },
  regionalServices: { eyebrow: "Paslaugos visame regione", title: "Viena bendra aptarnavimo teritorija pagrindinėms gyvenamųjų namų paslaugoms.", description: "Šildymo, šilumos siurblių, santechnikos ir skubaus remonto užklausoms taikoma ta pati bendra geografinė teritorija. Kiekviena užklausa vis tiek tikrinama pagal vietą ir darbų apimtį.", items: [
    { title: lithuanianNavigationLabels.heating, description: "Šildymo sistemų montavimas, remontas, priežiūra ir atnaujinimas gyvenamuosiuose objektuose.", path: "/heating", linkLabel: lithuanianHomeContent.services.items[0].link.label }, { title: lithuanianNavigationLabels.heatPumps, description: "Užklausos dėl šilumos siurblių tinkamumo, įvertinimo ir planuojamo montavimo.", path: "/heat-pumps", linkLabel: lithuanianHeatingContent.relatedServices.items[0].linkLabel }, { title: lithuanianNavigationLabels.plumbing, description: "Bendrieji buitinės santechnikos remonto, pakeitimo ir renovacijos darbai.", path: "/plumbing", linkLabel: lithuanianHomeContent.services.items[2].link.label }, { title: lithuanianNavigationLabels.emergencyRepairs, description: "Skubaus šildymo ir santechnikos remonto užklausos, vertinamos pagal pateiktą problemą ir vietą.", path: "/emergency-repairs", linkLabel: lithuanianHomeContent.enquiry.emergencyLink.label },
  ] },
  ruralProperties: { eyebrow: "Kaimo ir atokesni objektai", title: "Aptarnaujame ne tik didesnes gyvenvietes.", description: "Žemaitijoje yra ne tik didesni miestai ir miesteliai, bet ir kaimai bei atokiau esantys namai. Tokie objektai vertinami pagal tą pačią vietos ir darbų informaciją kaip ir kitos užklausos.", noteTitle: "Nurodykite tikslią objekto vietą", noteDescription: "Tikslus adresas arba aiški vietos informacija ypač naudinga, kai objektas yra atokesnėje vietovėje. Tai leidžia patikrinti aptarnavimo galimybę neapsimetant, kad egzistuoja visiškai tiksli riba ar automatinis priėmimas." },
  finalCta: { title: "Ar jūsų objektas patenka į įprastą aptarnavimo teritoriją?", description: "Nurodykite objekto vietą ir reikalingą šildymo, šilumos siurblio, santechnikos ar remonto paslaugą. Galėsime patikrinti aptarnavimo galimybę ir aptarti tinkamus tolesnius veiksmus.", contactLabel: "Patikrinti aptarnavimo galimybę" },
} as const satisfies ServiceAreaPageContent;

export const metadata = createLocalizedPageMetadata({ ...lithuanianServiceAreaContent.metadata, path: "/service-area", locale: "lt" });
export default function LithuanianServiceAreaPage() { return <ServiceAreaPage content={lithuanianServiceAreaContent} locale="lt" />; }
